Repository DedSecInside/ReFleX, pull requests merged in 2020-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: good first issue

#4 Readme update
  README.md
Labels: Hacktoberfest, documentation, good first issue

#7 Project directory structure (#6)
  CHANGELOG.md
  src/__init__.py
  src/core/__init__.py
  tests/__init__.py
Labels: Hacktoberfest, good first issue
